Models/Person.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;

namespace TestApsProject.Models
{
    public class Name
    {
        [Key]
        public int NameId { get; set; }
        public string first { get; set; }
        public string last { get; set; }

        //public int PersonId { get; set; }
        //public Person Person { get; set; }

        public override string ToString()
        {
            return $"{first} {last}";
        }
    }

    public class Friend
    {
        [Key]
        public int FriendId { get; set; }
        public int id { get; set; }
        public string name { get; set; }

        //public int PersonId { get; set; }
        //public Person Person { get; set; }

        public override string ToString()
        {
            return $"id: {id}, name: {name}";
        }
    }

    public class Person
    {
        [Key]
        //public int PersonId { get; set; }
        public string _id { get; set; }
        public int index { get; set; }
        public string balance { get; set; }
        public string picture { get; set; }
        public int age { get; set; }
        public string eyeColor { get; set; }
        public Name name { get; set; }
        public string company { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string address { get; set; }
        public string about { get; set; }
        public List<string> tags { get; set; }
        public List<Friend> friends { get; set; }
        public string favoriteFruit { get; set; }
    }
}

Controllers/ErrorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace TestApsProject.Controllers
{
    public class ErrorController : Controller
    {
        public IActionResult Index(int code)
        {
            ViewBag.ErrorCode = code;
            
            return View();
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

using System.Text.Json;

namespace TestApsProject.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return Redirect("~/Person");
        }

        public IActionResult Hello(string name)
        {
            ViewBag.Name = name;
            return View();
        }

        public IActionResult GetData()
        {
            string json = System.IO.File.ReadAllText(@"Data\sample.json");
            List<Models.Person> people = JsonSerializer.Deserialize<List<Models.Person>>(json);

            return View(people);
        }
    }
}

Controllers/PersonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

using Microsoft.EntityFrameworkCore;

namespace TestApsProject.Controllers
{
    public class PersonController : Controller
    {
        public IActionResult Index()
        {
            List<Models.Person> people;
            using (var dataContext = new Data.DataContext())
            {
                people = dataContext.People.Include(p => p.name).ToList();
            }
            return View(people);
        }


        [HttpGet]
        public ActionResult Details(string id)
        {
            Models.Person person;
            using (var dataContext = new Data.DataContext())
            {
                person = dataContext.People
                    .Include(p => p.name)
                    .Include(p => p.friends)
                    .FirstOrDefault(p => p._id == id);
            }
            return View(person);
        }


        [HttpGet]
        public ActionResult Delete(string id)
        {
            Models.Person person;
            using (var dataContext = new Data.DataContext())
            {
                person = dataContext.People
                    .Include(p => p.name)
                    .Include(p => p.friends)
                    .FirstOrDefault(p => p._id == id);
            }
            return View(person);
        }

        [HttpPost]
        public ActionResult DeletePerson(string id)
        {
            using (var dataContext = new Data.DataContext())
            {
                Models.Person person = dataContext.People
                    .Include(p => p.name)
                    .Include(p => p.friends)
                    .FirstOrDefault(p => p._id == id);
                dataContext.People.Remove(person);
                dataContext.SaveChanges();
            }
            return RedirectToAction("Index");
        }


        [HttpGet]
        public ActionResult Edit(string id)
        {
            Models.Person person;
            using (var dataContext = new Data.DataContext())
            {
                person = dataContext.People
                    .Include(p => p.name)
                    .Include(p => p.friends)
                    .FirstOrDefault(p => p._id == id);
            }
            return View(person);
        }

        [HttpPost]
        public ActionResult Edit(Models.Person person)
        {
            person.tags.Remove(null);
            Models.Person person_to_edit;
            using (var dataContext = new Data.DataContext())
            {
                person_to_edit = dataContext.People.Find(person._id);
                dataContext.Entry(person_to_edit).State = EntityState.Detached;
                dataContext.People.Attach(person);
                dataContext.Entry(person).State = EntityState.Modified;

                dataContext.SaveChanges();
            }
            return RedirectToAction("Index");
        }


        [HttpGet]
        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Add(Models.Person person)
        {
            person.tags = new List<string>();
            person.friends = new List<Models.Friend>();
            using (var dataContext = new Data.DataContext())
            {
                dataContext.Add(person);
                dataContext.SaveChanges();
            }
            return RedirectToAction("Index");
        }
    }
}

Controllers/TestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

using TestApsProject.Services;

namespace TestApsProject.Controllers
{
    public class TestController : Controller
    {
        private IDateTimeHandler dateTimeHandler;
        public TestController(IDateTimeHandler handler)
        {
            dateTimeHandler = handler;
        }

        public IActionResult Index()
        {
            return View();
        }

        public string GetString()
        {
            return "Hello";
        }

        public string Hello(string name)
        {
            return $"Hello, {name}.";
        }

        public string GetDayOfYear()
        {
            return DateTime.Now.DayOfYear.ToString();
        }

        public string GetTime()
        {
            //int hour = DateTime.Now.Hour;
            //string message;

            //if (hour < 5)
            //{
            //    message = "Доброй ночи!";
            //}
            //else if (hour < 12)
            //{
            //    message = "Доброе утро!";
            //}
            //else if (hour < 16)
            //{
            //    message = "Добрый день!";
            //}
            //else
            //{
            //    message = "Добрый вечер!";
            //}

            //return $"{message} Сейчас {DateTime.Now.ToString("t")}.";

            return dateTimeHandler.ConvertDateTimeToString(DateTime.Now);
        }

        public string Sum(int a, int b)
        {
            return (a + b).ToString();
        }

        public string ErrorMaker()
        {
            int a = 0;
            int b = 1 / a;

            return "))))";
        }
    }
}

Views/Home/GetData.cshtml
@{
    ViewData["Title"] = "GetData";
}
<table id="myTable" class="table" cellspacing="0">
    <thead>
        <tr>
            @foreach (var property in Model.GetType().GetGenericArguments()[0].GetProperties())
            {
                <th>@property.Name</th>
            }
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                @foreach (var property in item.GetType().GetProperties())
                {
                <td>
                    @if (property.Name == "picture")
                    {
                        <img src="@property.GetValue(item)">
                    }
                    else if (property.Name == "tags" || property.Name == "friends")
                    {
                        foreach(var listMember in @property.GetValue(item))
                        {
                            @(listMember.ToString()+"\n")
                        }
                    }
                    else
                    {
                        @property.GetValue(item)
                    }
                </td>
                }
            </tr>
        }
    </tbody>
</table>

Views/Home/Hello.cshtml
@{
    ViewData["Title"] = "Hello";
}

<h1>Hello @ViewBag.Name!</h1>

Views/Person/Add.cshtml
@model TestApsProject.Models.Person
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Add</title>
</head>
<body>

    <h4>Person</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Add">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="_id" class="control-label"></label>
                    <input asp-for="_id" class="form-control" />
                    <span asp-validation-for="_id" class="text-danger"></span>
                </div>
                @*<div class="form-group">
            <label asp-for="index" class="control-label"></label>
            <input asp-for="index" class="form-control" />
            <span asp-validation-for="index" class="text-danger"></span>
        </div>*@
                <div class="form-group">
                    <label asp-for="balance" class="control-label"></label>
                    <input asp-for="balance" class="form-control" />
                    <span asp-validation-for="balance" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="picture" class="control-label"></label>
                    <input asp-for="picture" class="form-control" />
                    <span asp-validation-for="picture" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="age" class="control-label"></label>
                    <input asp-for="age" class="form-control" />
                    <span asp-validation-for="age" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="eyeColor" class="control-label"></label>
                    <input asp-for="eyeColor" class="form-control" />
                    <span asp-validation-for="eyeColor" class="text-danger"></span>
                </div>
                names:
                <div class="form-group">
                    <label asp-for="name.first" class="control-label"></label>
                    <input asp-for="name.first" class="form-control" />
                    <span asp-validation-for="name.first" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="name.last" class="control-label"></label>
                    <input asp-for="name.last" class="form-control" />
                    <span asp-validation-for="name.last" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="company" class="control-label"></label>
                    <input asp-for="company" class="form-control" />
                    <span asp-validation-for="company" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="email" class="control-label"></label>
                    <input asp-for="email" class="form-control" />
                    <span asp-validation-for="email" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="phone" class="control-label"></label>
                    <input asp-for="phone" class="form-control" />
                    <span asp-validation-for="phone" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="address" class="control-label"></label>
                    <input asp-for="address" class="form-control" />
                    <span asp-validation-for="address" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="about" class="control-label"></label>
                    <input asp-for="about" class="form-control" />
                    <span asp-validation-for="about" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="favoriteFruit" class="control-label"></label>
                    <input asp-for="favoriteFruit" class="form-control" />
                    <span asp-validation-for="favoriteFruit" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="Index">Back to List</a>
    </div>

</body>
</html>

Views/Person/Delete.cshtml
@model TestApsProject.Models.Person
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>

    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>Person</h4>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model._id)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model._id)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.index)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.index)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.balance)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.balance)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.picture)
            </dt>
            <dd class="col-sm-10">
                <img src="@Html.DisplayFor(model => model.picture)">
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.age)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.age)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.eyeColor)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.eyeColor)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.name)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.name)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.company)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.company)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.email)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.email)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.phone)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.phone)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.address)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.address)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.about)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.about)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.tags)
            </dt>
            <dd class="col-sm-10">
                @String.Join("; ", Model.tags)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.friends)
            </dt>
            <dd class="col-sm-10">
                @Html.Raw(String.Join(@";<br />", Model.friends))
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.favoriteFruit)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.favoriteFruit)
            </dd>
        </dl>

        @*<form asp-action="DeletePerson">
            <input type="hidden" name="personId" value="@Model._id" />
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            <a asp-action="Index">Back to List</a>
        </form>*@
        @using (Html.BeginForm("DeletePerson", "Person", FormMethod.Post))
        {
            <input type="hidden" value="@Model._id" name="id" />
            <input type="submit" value="Delete" class="btn btn-danger" />
            <a asp-action="Index">Back to List</a>
        }
    </div>
</body>
</html>

Views/Person/Details.cshtml
@model TestApsProject.Models.Person
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>

    <div>
        <h4>Person</h4>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model._id)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model._id)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.index)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.index)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.balance)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.balance)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.picture)
            </dt>
            <dd class="col-sm-10">
                <img src="@Html.DisplayFor(model => model.picture)">
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.age)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.age)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.eyeColor)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.eyeColor)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.name)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.name)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.company)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.company)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.email)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.email)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.phone)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.phone)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.address)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.address)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.about)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.about)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.tags)
            </dt>
            <dd class="col-sm-10">
                @String.Join("; ", Model.tags)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.friends)
            </dt>
            <dd class="col-sm-10">
                @Html.Raw(String.Join(@";<br />", Model.friends))
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.favoriteFruit)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.favoriteFruit)
            </dd>
        </dl>
    </div>
    <div>
        @Html.ActionLink("Edit", "Edit", new { id = Model._id }) |
        <a asp-action="Index">Back to List</a>
    </div>
</body>
</html>

Views/Person/Edit.cshtml
@model TestApsProject.Models.Person
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    Layout = "_Layout";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>

    <h4>Person</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                @*<div class="form-group">
                        <label asp-for="_id" class="control-label"></label>
                        <input asp-for="_id" class="form-control" />
                        <span asp-validation-for="_id" class="text-danger"></span>
                    </div>*@
                <input type="hidden" value="@Model._id" asp-for="_id" />
                <div class="form-group">
                    <label asp-for="index" class="control-label"></label>
                    <input asp-for="index" class="form-control" />
                    <span asp-validation-for="index" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="balance" class="control-label"></label>
                    <input asp-for="balance" class="form-control" />
                    <span asp-validation-for="balance" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="picture" class="control-label"></label>
                    <input asp-for="picture" class="form-control" />
                    <span asp-validation-for="picture" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="age" class="control-label"></label>
                    <input asp-for="age" class="form-control" />
                    <span asp-validation-for="age" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="eyeColor" class="control-label"></label>
                    <input asp-for="eyeColor" class="form-control" />
                    <span asp-validation-for="eyeColor" class="text-danger"></span>
                </div>
                names:
                <div class="form-group">
                    <label asp-for="name.first" class="control-label"></label>
                    <input asp-for="name.first" class="form-control" />
                    <span asp-validation-for="name.first" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="name.last" class="control-label"></label>
                    <input asp-for="name.last" class="form-control" />
                    <span asp-validation-for="name.last" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="company" class="control-label"></label>
                    <input asp-for="company" class="form-control" />
                    <span asp-validation-for="company" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="email" class="control-label"></label>
                    <input asp-for="email" class="form-control" />
                    <span asp-validation-for="email" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="phone" class="control-label"></label>
                    <input asp-for="phone" class="form-control" />
                    <span asp-validation-for="phone" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="address" class="control-label"></label>
                    <input asp-for="address" class="form-control" />
                    <span asp-validation-for="address" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="about" class="control-label"></label>
                    <textarea asp-for="about" class="form-control"></textarea>
                    <span asp-validation-for="about" class="text-danger"></span>
                </div>
                <div class="form-group" id="tags">
                    <script>
                            $(document).ready(function () {
                                $(document).on('click', ".tag-del-btn", function () {
                                    $(this).parent().hide();
                                    $(this).siblings(".tag-tb").val("");
                                })
                            })
                    </script>
                    <p>tags:</p>
                    @for (int i = 0; i < Model.tags.Count; i++)
                    {
                        <div>
                            @Html.TextBoxFor(m => Model.tags[i], Model.tags[i], new { @class = "tag-tb" })
                            <button type="button" class="tag-del-btn">-</button>
                        </div>
                    }
                </div>
                <div>
                    <script>
                        $(document).ready(function () {
                            var next_i = @Model.tags.Count;
                            $("#create_btn").click(function () {
                                var tb = document.createElement("input");
                                tb.type = "text";
                                tb.className = "tag-tb";
                                tb.id = `tags_${next_i}_`;
                                tb.name = `tags[${next_i}]`;
                                var btn = document.createElement("button");
                                btn.type = "button";
                                btn.textContent = "-";
                                btn.className = 'tag-del-btn';
                                $("#tags").append(tb)
                                $("#tags").append(btn);
                                $([tb, btn]).wrapAll("<div></div>");
                                next_i++;
                            })
                        })
                    </script>
                    <button type="button" id="create_btn">+</button>
                </div>
                <div class="form-group">
                    friends:
                    @for (int i = 0; i < Model.friends.Count; i++)
                    {
                        <div>
                            @Html.LabelFor(m => Model.friends[i].id)
                            @Html.TextBoxFor(m => Model.friends[i].id)
                        </div>
                        <div>
                            @Html.LabelFor(m => Model.friends[i].name)
                            @Html.TextBoxFor(m => Model.friends[i].name)
                        </div>
                    }
                </div>
                <div class="form-group">
                    <label asp-for="favoriteFruit" class="control-label"></label>
                    <input asp-for="favoriteFruit" class="form-control" />
                    <span asp-validation-for="favoriteFruit" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="Index">Back to List</a>
    </div>

</body>
</html>

Views/Person/Index.cshtml
@model IEnumerable<TestApsProject.Models.Person>
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <p>
        <a asp-action="Add">Create New</a>
    </p>
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model._id)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.picture)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item._id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.name)
                    </td>
                    <td>
                        <img src="@Html.DisplayFor(modelItem => item.picture)">
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id=item._id }) |
                        @Html.ActionLink("Details", "Details", new { id=item._id }) |
                        @Html.ActionLink("Delete", "Delete", new { id=item._id })
                    </td>
                </tr>
            }
        </tbody>
    </table>
</body>
</html>

Views/Shared/DisplayTemplates/Name.cshtml
@model TestApsProject.Models.Name

@if (Model == null)
{
    <strong>Null name</strong>
}
else
{
    @Model.first@:&nbsp;@Model.last
}